//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_QPROINSPECTLIST
    {
        public Nullable<System.Guid> INSPECTGUID { get; set; }
        public int ID { get; set; }
        public string CVOUCHTYPE { get; set; }
        public string CINSPECTCODE { get; set; }
        public string CREJECTCODE { get; set; }
        public string CSOURCECODE { get; set; }
        public Nullable<int> REJECTID { get; set; }
        public Nullable<int> CSOURCEID { get; set; }
        public Nullable<System.DateTime> DARRIVALDATE { get; set; }
        public string CDEPCODE { get; set; }
        public string CDEPNAME { get; set; }
        public string CINSPECTDEPCODE { get; set; }
        public string CINSPECTDEPNAME { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string CTIME { get; set; }
        public string CSOURCE { get; set; }
        public Nullable<int> IVTID { get; set; }
        public string UFTS { get; set; }
        public string CMAKER { get; set; }
        public string CVERIFIER { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public Nullable<System.DateTime> CDEFINE4 { get; set; }
        public Nullable<int> CDEFINE5 { get; set; }
        public Nullable<System.DateTime> CDEFINE6 { get; set; }
        public Nullable<decimal> CDEFINE7 { get; set; }
        public string CDEFINE8 { get; set; }
        public string CDEFINE9 { get; set; }
        public string CDEFINE10 { get; set; }
        public string CDEFINE11 { get; set; }
        public string CDEFINE12 { get; set; }
        public string CDEFINE13 { get; set; }
        public string CDEFINE14 { get; set; }
        public Nullable<int> CDEFINE15 { get; set; }
        public Nullable<decimal> CDEFINE16 { get; set; }
        public int AUTOID { get; set; }
        public string CITEMCLASS { get; set; }
        public string CITEMCODE { get; set; }
        public string CITEMCNAME { get; set; }
        public string CITEMNAME { get; set; }
        public Nullable<int> REJECTAUTOID { get; set; }
        public Nullable<int> SOURCEAUTOID { get; set; }
        public int ITESTSTYLE { get; set; }
        public string CINVCODE { get; set; }
        public string CINVNAME { get; set; }
        public string CINVSTD { get; set; }
        public string CCOMUNITCODE { get; set; }
        public string CCOMUNITNAME { get; set; }
        public string CBATCH { get; set; }
        public string CPROBATCH { get; set; }
        public Nullable<System.DateTime> DPRODATE { get; set; }
        public Nullable<System.DateTime> DVDATE { get; set; }
        public string CUNITID { get; set; }
        public string CUNITNAME { get; set; }
        public Nullable<decimal> FCHANGRATE { get; set; }
        public Nullable<decimal> FQUANTITY { get; set; }
        public Nullable<decimal> FNUM { get; set; }
        public bool BFLAG { get; set; }
        public string CFREE1 { get; set; }
        public string CFREE2 { get; set; }
        public string CFREE3 { get; set; }
        public string CFREE4 { get; set; }
        public string CFREE5 { get; set; }
        public string CFREE6 { get; set; }
        public string CFREE7 { get; set; }
        public string CFREE8 { get; set; }
        public string CFREE9 { get; set; }
        public string CFREE10 { get; set; }
        public string CDEFINE22 { get; set; }
        public string CDEFINE23 { get; set; }
        public string CDEFINE24 { get; set; }
        public string CDEFINE25 { get; set; }
        public Nullable<decimal> CDEFINE26 { get; set; }
        public Nullable<decimal> CDEFINE27 { get; set; }
        public string CDEFINE28 { get; set; }
        public string CDEFINE29 { get; set; }
        public string CDEFINE30 { get; set; }
        public string CDEFINE31 { get; set; }
        public string CDEFINE32 { get; set; }
        public string CDEFINE33 { get; set; }
        public Nullable<int> CDEFINE34 { get; set; }
        public Nullable<int> CDEFINE35 { get; set; }
        public Nullable<System.DateTime> CDEFINE36 { get; set; }
        public Nullable<System.DateTime> CDEFINE37 { get; set; }
        public string CINVDEFINE1 { get; set; }
        public string CINVDEFINE2 { get; set; }
        public string CINVDEFINE3 { get; set; }
        public string CINVDEFINE4 { get; set; }
        public string CINVDEFINE5 { get; set; }
        public string CINVDEFINE6 { get; set; }
        public string CINVDEFINE7 { get; set; }
        public string CINVDEFINE8 { get; set; }
        public string CINVDEFINE9 { get; set; }
        public string CINVDEFINE10 { get; set; }
        public Nullable<int> CINVDEFINE11 { get; set; }
        public Nullable<int> CINVDEFINE12 { get; set; }
        public Nullable<double> CINVDEFINE13 { get; set; }
        public Nullable<double> CINVDEFINE14 { get; set; }
        public Nullable<System.DateTime> CINVDEFINE15 { get; set; }
        public Nullable<System.DateTime> CINVDEFINE16 { get; set; }
        public Nullable<int> IID { get; set; }
        public string CCUSNAME { get; set; }
        public string CCUSCODE { get; set; }
        public Nullable<int> IPROORDERID { get; set; }
        public string CPROORDERCODE { get; set; }
        public Nullable<int> IPROORDERAUTOID { get; set; }
        public Nullable<int> IORDERTYPE { get; set; }
        public string CSOORDERCODE { get; set; }
        public string ISOORDERAUTOID { get; set; }
        public string CCONTRACTCODE { get; set; }
        public string CCONTRACTSTRCODE { get; set; }
        public bool BEXIGENCY { get; set; }
        public string CCHECKTYPECODE { get; set; }
        public string CCHECKTYPENAME { get; set; }
        public string CBYPRODUCT { get; set; }
        public string CMASSUNIT { get; set; }
        public Nullable<short> IMASSDATE { get; set; }
        public string CWHCODE { get; set; }
        public string CWHNAME { get; set; }
        public string CINVADDCODE { get; set; }
        public string CWORKCENTER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> IWORKCENTER { get; set; }
        public Nullable<int> IROWNO { get; set; }
        public string CRCLASSNAME { get; set; }
        public Nullable<decimal> FSUMCHECKQTY { get; set; }
        public Nullable<decimal> FSUMCHECKNUM { get; set; }
        public Nullable<decimal> FUNCHECKQTY { get; set; }
        public Nullable<decimal> FUNCHECKNUM { get; set; }
        public Nullable<decimal> FBCCHECKQTY { get; set; }
        public Nullable<decimal> FBCCHECKNUM { get; set; }
        public byte IGROUPTYPE { get; set; }
        public string CCONTRACTROWNO { get; set; }
        public string CMODIFIER { get; set; }
        public Nullable<System.DateTime> DMAKETIME { get; set; }
        public Nullable<System.DateTime> DMODIFYDATE { get; set; }
        public Nullable<System.DateTime> DVERIFYDATE { get; set; }
        public Nullable<System.DateTime> DMODIFYTIME { get; set; }
        public Nullable<System.DateTime> DVERIFYTIME { get; set; }
        public string CSOURCEPROORDERCODE { get; set; }
        public Nullable<int> ISOURCEPROORDERROWNO { get; set; }
        public Nullable<int> ISOURCEPROORDERID { get; set; }
        public Nullable<int> ISOURCEPROORDERAUTOID { get; set; }
        public Nullable<short> IEXPIRATDATECALCU { get; set; }
        public string CEXPIRATIONDATE { get; set; }
        public Nullable<System.DateTime> DEXPIRATIONDATE { get; set; }
        public Nullable<byte> MO_STATUS { get; set; }
        public Nullable<decimal> CBATCHPROPERTY1 { get; set; }
        public Nullable<decimal> CBATCHPROPERTY2 { get; set; }
        public Nullable<decimal> CBATCHPROPERTY3 { get; set; }
        public Nullable<decimal> CBATCHPROPERTY4 { get; set; }
        public Nullable<decimal> CBATCHPROPERTY5 { get; set; }
        public string CBATCHPROPERTY6 { get; set; }
        public string CBATCHPROPERTY7 { get; set; }
        public string CBATCHPROPERTY8 { get; set; }
        public string CBATCHPROPERTY9 { get; set; }
        public Nullable<System.DateTime> CBATCHPROPERTY10 { get; set; }
        public Nullable<int> IPRINTCOUNT { get; set; }
        public string CSYSBARCODE { get; set; }
        public string CBSYSBARCODE { get; set; }
        public int DOCSTATE { get; set; }
        public string CCHECKCODE { get; set; }
        public string PLANLOTNUMBER { get; set; }
        public Nullable<bool> BMERGECHECKFLAG { get; set; }
    }
}
