//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingDan_WebForm.SMS9002 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS9002.SendSMS2CustomerSoap")]
    public interface SendSMS2CustomerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_Old", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendSMS_Old(string num, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_Old", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendSMS_OldAsync(string num, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendSMS(string mobiles, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendSMSAsync(string mobiles, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveSMSReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ReceiveSMSReport(string report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveSMSReport", ReplyAction="*")]
        System.Threading.Tasks.Task ReceiveSMSReportAsync(string report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getreport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DingDan_WebForm.SMS9002.StatusReportModel[] getreport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getreport", ReplyAction="*")]
        System.Threading.Tasks.Task<DingDan_WebForm.SMS9002.StatusReportModel[]> getreportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSubmitReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DingDan_WebForm.SMS9002.SubmitReportModel[] getSubmitReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSubmitReport", ReplyAction="*")]
        System.Threading.Tasks.Task<DingDan_WebForm.SMS9002.SubmitReportModel[]> getSubmitReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert_Report();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Report", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Insert_ReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFHSMS2Customer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendFHSMS2Customer(string phoneno, string orderno, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFHSMS2Customer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendFHSMS2CustomerAsync(string phoneno, string orderno, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_access_token", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_access_token();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_access_token", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Get_access_tokenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendQY_Message_Text", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendQY_Message_Text(string touser, string toparty, string totag, string agentid, string strWxMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendQY_Message_Text", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendQY_Message_TextAsync(string touser, string toparty, string totag, string agentid, string strWxMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendQY_Message_Image", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendQY_Message_Image(string touser, string toparty, string totag, string agentid, string title, string description, string url, string picurl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendQY_Message_Image", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendQY_Message_ImageAsync(string touser, string toparty, string totag, string agentid, string title, string description, string url, string picurl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeQR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MakeQR(string content, string MAACode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeQR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MakeQRAsync(string content, string MAACode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusReportModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileField;
        
        private string submitDateField;
        
        private string receiveDateField;
        
        private string errorCodeField;
        
        private string msgGroupField;
        
        private string reportStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
                this.RaisePropertyChanged("submitDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("receiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string msgGroup {
            get {
                return this.msgGroupField;
            }
            set {
                this.msgGroupField = value;
                this.RaisePropertyChanged("msgGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reportStatus {
            get {
                return this.reportStatusField;
            }
            set {
                this.reportStatusField = value;
                this.RaisePropertyChanged("reportStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitReportModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] mobilesField;
        
        private string submitDateField;
        
        private string receiveDateField;
        
        private string errorCodeField;
        
        private string msgGroupField;
        
        private string reportStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] mobiles {
            get {
                return this.mobilesField;
            }
            set {
                this.mobilesField = value;
                this.RaisePropertyChanged("mobiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string submitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
                this.RaisePropertyChanged("submitDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("receiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string msgGroup {
            get {
                return this.msgGroupField;
            }
            set {
                this.msgGroupField = value;
                this.RaisePropertyChanged("msgGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reportStatus {
            get {
                return this.reportStatusField;
            }
            set {
                this.reportStatusField = value;
                this.RaisePropertyChanged("reportStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMS2CustomerSoapChannel : DingDan_WebForm.SMS9002.SendSMS2CustomerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMS2CustomerSoapClient : System.ServiceModel.ClientBase<DingDan_WebForm.SMS9002.SendSMS2CustomerSoap>, DingDan_WebForm.SMS9002.SendSMS2CustomerSoap {
        
        public SendSMS2CustomerSoapClient() {
        }
        
        public SendSMS2CustomerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMS2CustomerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMS2CustomerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMS2CustomerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendSMS_Old(string num, string content) {
            return base.Channel.SendSMS_Old(num, content);
        }
        
        public System.Threading.Tasks.Task<bool> SendSMS_OldAsync(string num, string content) {
            return base.Channel.SendSMS_OldAsync(num, content);
        }
        
        public bool SendSMS(string mobiles, string content) {
            return base.Channel.SendSMS(mobiles, content);
        }
        
        public System.Threading.Tasks.Task<bool> SendSMSAsync(string mobiles, string content) {
            return base.Channel.SendSMSAsync(mobiles, content);
        }
        
        public void ReceiveSMSReport(string report) {
            base.Channel.ReceiveSMSReport(report);
        }
        
        public System.Threading.Tasks.Task ReceiveSMSReportAsync(string report) {
            return base.Channel.ReceiveSMSReportAsync(report);
        }
        
        public DingDan_WebForm.SMS9002.StatusReportModel[] getreport() {
            return base.Channel.getreport();
        }
        
        public System.Threading.Tasks.Task<DingDan_WebForm.SMS9002.StatusReportModel[]> getreportAsync() {
            return base.Channel.getreportAsync();
        }
        
        public DingDan_WebForm.SMS9002.SubmitReportModel[] getSubmitReport() {
            return base.Channel.getSubmitReport();
        }
        
        public System.Threading.Tasks.Task<DingDan_WebForm.SMS9002.SubmitReportModel[]> getSubmitReportAsync() {
            return base.Channel.getSubmitReportAsync();
        }
        
        public bool Insert_Report() {
            return base.Channel.Insert_Report();
        }
        
        public System.Threading.Tasks.Task<bool> Insert_ReportAsync() {
            return base.Channel.Insert_ReportAsync();
        }
        
        public string SendFHSMS2Customer(string phoneno, string orderno, string content) {
            return base.Channel.SendFHSMS2Customer(phoneno, orderno, content);
        }
        
        public System.Threading.Tasks.Task<string> SendFHSMS2CustomerAsync(string phoneno, string orderno, string content) {
            return base.Channel.SendFHSMS2CustomerAsync(phoneno, orderno, content);
        }
        
        public string Get_access_token() {
            return base.Channel.Get_access_token();
        }
        
        public System.Threading.Tasks.Task<string> Get_access_tokenAsync() {
            return base.Channel.Get_access_tokenAsync();
        }
        
        public bool SendQY_Message_Text(string touser, string toparty, string totag, string agentid, string strWxMessage) {
            return base.Channel.SendQY_Message_Text(touser, toparty, totag, agentid, strWxMessage);
        }
        
        public System.Threading.Tasks.Task<bool> SendQY_Message_TextAsync(string touser, string toparty, string totag, string agentid, string strWxMessage) {
            return base.Channel.SendQY_Message_TextAsync(touser, toparty, totag, agentid, strWxMessage);
        }
        
        public bool SendQY_Message_Image(string touser, string toparty, string totag, string agentid, string title, string description, string url, string picurl) {
            return base.Channel.SendQY_Message_Image(touser, toparty, totag, agentid, title, description, url, picurl);
        }
        
        public System.Threading.Tasks.Task<bool> SendQY_Message_ImageAsync(string touser, string toparty, string totag, string agentid, string title, string description, string url, string picurl) {
            return base.Channel.SendQY_Message_ImageAsync(touser, toparty, totag, agentid, title, description, url, picurl);
        }
        
        public string MakeQR(string content, string MAACode) {
            return base.Channel.MakeQR(content, MAACode);
        }
        
        public System.Threading.Tasks.Task<string> MakeQRAsync(string content, string MAACode) {
            return base.Channel.MakeQRAsync(content, MAACode);
        }
    }
}
