//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public Reason()
        {
            this.QMCHECKVOUCHER = new HashSet<QMCHECKVOUCHER>();
            this.QMREJECTVOUCHERS = new HashSet<QMREJECTVOUCHERS>();
        }
    
        public string cReasonCode { get; set; }
        public string cReasonName { get; set; }
        public byte iReasontype { get; set; }
        public string cReasonMemo { get; set; }
        public byte[] pubufts { get; set; }
    
        public virtual ICollection<QMCHECKVOUCHER> QMCHECKVOUCHER { get; set; }
        public virtual ICollection<QMREJECTVOUCHERS> QMREJECTVOUCHERS { get; set; }
    }
}
