//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sfc_workcenter
    {
        public sfc_workcenter()
        {
            this.QMCHECKVOUCHER = new HashSet<QMCHECKVOUCHER>();
            this.QMINSPECTVOUCHER = new HashSet<QMINSPECTVOUCHER>();
            this.QMREJECTVOUCHER = new HashSet<QMREJECTVOUCHER>();
        }
    
        public int WcId { get; set; }
        public string WcCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public Nullable<bool> ProductLineFlag { get; set; }
        public string DeptCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<int> UpdCount { get; set; }
        public byte[] Ufts { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<QMCHECKVOUCHER> QMCHECKVOUCHER { get; set; }
        public virtual ICollection<QMINSPECTVOUCHER> QMINSPECTVOUCHER { get; set; }
        public virtual ICollection<QMREJECTVOUCHER> QMREJECTVOUCHER { get; set; }
    }
}
