//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_fc_refermoroutingmixedlist
    {
        public int moid { get; set; }
        public int modid { get; set; }
        public string mocode { get; set; }
        public int sortseq { get; set; }
        public string motypedesc { get; set; }
        public string invcode { get; set; }
        public string cinvname { get; set; }
        public string cinvstd { get; set; }
        public string cinvaddcode { get; set; }
        public string molotcode { get; set; }
        public string cengineerfigno { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string ccomunitcode { get; set; }
        public string ccomunitname { get; set; }
        public Nullable<byte> status { get; set; }
        public string modescription { get; set; }
        public string SoCode { get; set; }
        public Nullable<int> SoSeq { get; set; }
        public string free1 { get; set; }
        public string free2 { get; set; }
        public string free3 { get; set; }
        public string free4 { get; set; }
        public string free5 { get; set; }
        public string free6 { get; set; }
        public string free7 { get; set; }
        public string free8 { get; set; }
        public string free9 { get; set; }
        public string free10 { get; set; }
        public string cinvdefine1 { get; set; }
        public string cinvdefine2 { get; set; }
        public string cinvdefine3 { get; set; }
        public string cinvdefine4 { get; set; }
        public string cinvdefine5 { get; set; }
        public string cinvdefine6 { get; set; }
        public string cinvdefine7 { get; set; }
        public string cinvdefine8 { get; set; }
        public string cinvdefine9 { get; set; }
        public string cinvdefine10 { get; set; }
        public Nullable<int> cinvdefine11 { get; set; }
        public Nullable<int> cinvdefine12 { get; set; }
        public Nullable<double> cinvdefine13 { get; set; }
        public Nullable<double> cinvdefine14 { get; set; }
        public Nullable<System.DateTime> cinvdefine15 { get; set; }
        public Nullable<System.DateTime> cinvdefine16 { get; set; }
        public string MdeptCode { get; set; }
        public string cdepname { get; set; }
        public int moroutingid { get; set; }
        public int moroutingdid { get; set; }
        public string opseq { get; set; }
        public string opcode { get; set; }
        public string opdescription { get; set; }
        public Nullable<bool> subflag { get; set; }
        public Nullable<int> wcid { get; set; }
        public string wccode { get; set; }
        public string wcdescription { get; set; }
        public string wcdepcode { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> duetime { get; set; }
        public string inopunitcode { get; set; }
        public string inopunitname { get; set; }
        public Nullable<decimal> inchangerate { get; set; }
        public Nullable<decimal> inauxopqty { get; set; }
        public Nullable<decimal> balmachiningqty { get; set; }
        public Nullable<decimal> baldeclareqty { get; set; }
        public Nullable<decimal> balqualifiedqty { get; set; }
        public Nullable<decimal> balrefusedqty { get; set; }
        public Nullable<decimal> balscrapqty { get; set; }
        public Nullable<int> perworkhr { get; set; }
        public Nullable<bool> FirstFlag { get; set; }
        public Nullable<bool> LastFlag { get; set; }
        public Nullable<decimal> reportqty { get; set; }
        public Nullable<int> moroutingshiftid { get; set; }
        public decimal shiftqty { get; set; }
        public Nullable<decimal> moreportqty { get; set; }
        public Nullable<decimal> completedqty { get; set; }
        public Nullable<decimal> uncompletedqty { get; set; }
        public Nullable<int> eqid { get; set; }
        public string ceqcode { get; set; }
        public string ceqname { get; set; }
        public string employcode { get; set; }
        public string employname { get; set; }
        public string dutyclasscode { get; set; }
        public string dutyclassname { get; set; }
        public Nullable<int> workshiftid { get; set; }
        public string wscode { get; set; }
        public string bcdescription { get; set; }
        public Nullable<decimal> unreportqty { get; set; }
        public string cmoroutufts { get; set; }
        public string cshiftufts { get; set; }
        public int bscrap { get; set; }
        public Nullable<System.DateTime> shiftstartdate { get; set; }
        public Nullable<System.DateTime> shiftduedate { get; set; }
    }
}
