//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DL_U8_pgshift
    {
        public int moroutingid { get; set; }
        public int moroutingdid { get; set; }
        public int moid { get; set; }
        public int modid { get; set; }
        public string mocode { get; set; }
        public int moseq { get; set; }
        public Nullable<byte> moclass { get; set; }
        public string motypedesc { get; set; }
        public Nullable<byte> ordertype { get; set; }
        public Nullable<byte> status { get; set; }
        public string cinvcode { get; set; }
        public string cinvname { get; set; }
        public string cinvaddcode { get; set; }
        public string cinvstd { get; set; }
        public Nullable<decimal> moqty { get; set; }
        public string cdepcode { get; set; }
        public string cdepname { get; set; }
        public string opseq { get; set; }
        public string description { get; set; }
        public Nullable<bool> subflag { get; set; }
        public string wccode { get; set; }
        public string wcdescription { get; set; }
        public Nullable<int> moroutingshiftid { get; set; }
        public Nullable<int> sortseq { get; set; }
        public Nullable<int> workshiftid { get; set; }
        public string bccode { get; set; }
        public string bcdescription { get; set; }
        public string dutyclasscode { get; set; }
        public string dcdescription { get; set; }
        public Nullable<int> eqid { get; set; }
        public string ceqcode { get; set; }
        public string ceqname { get; set; }
        public string employcode { get; set; }
        public string employname { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> completedqty { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> duetime { get; set; }
        public Nullable<decimal> reportqty { get; set; }
        public Nullable<decimal> shiftqty { get; set; }
        public Nullable<decimal> unshiftqty { get; set; }
        public Nullable<decimal> perhour { get; set; }
        public Nullable<decimal> shifthour { get; set; }
        public Nullable<decimal> unshifthour { get; set; }
        public string define22 { get; set; }
        public string define23 { get; set; }
        public string define24 { get; set; }
        public string define25 { get; set; }
        public Nullable<double> define26 { get; set; }
        public Nullable<double> define27 { get; set; }
        public string define28 { get; set; }
        public string define29 { get; set; }
        public string define30 { get; set; }
        public string define31 { get; set; }
        public string define32 { get; set; }
        public string define33 { get; set; }
        public Nullable<int> define34 { get; set; }
        public Nullable<int> define35 { get; set; }
        public Nullable<System.DateTime> define36 { get; set; }
        public Nullable<System.DateTime> define37 { get; set; }
        public string ufts2 { get; set; }
        public string ufts { get; set; }
        public string editprop { get; set; }
        public string cInvCCode { get; set; }
        public Nullable<System.Guid> Id_ColumnName { get; set; }
    }
}
