//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_hi_person
    {
        public string cPsn_Num { get; set; }
        public string cPsn_Name { get; set; }
        public string cDept_num { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public string rPersonType { get; set; }
        public string rSex { get; set; }
        public string dBirthDate { get; set; }
        public string rNativePlace { get; set; }
        public string rNational { get; set; }
        public string rhealthStatus { get; set; }
        public string rMarriStatus { get; set; }
        public string vIDNo { get; set; }
        public byte[] MPicture { get; set; }
        public string rPerResidence { get; set; }
        public string vAliaName { get; set; }
        public string dJoinworkDate { get; set; }
        public string dEnterDate { get; set; }
        public string dRegularDate { get; set; }
        public string vSSNo { get; set; }
        public string rworkAttend { get; set; }
        public string vCardNo { get; set; }
        public string rtbmRule { get; set; }
        public string rCheckInFlag { get; set; }
        public string dLastDate { get; set; }
        public byte[] hrts { get; set; }
        public string vstatus1 { get; set; }
        public Nullable<decimal> nstatus2 { get; set; }
        public bool bPsnPerson { get; set; }
        public string cPsnMobilePhone { get; set; }
        public string cPsnFPhone { get; set; }
        public string cPsnOPhone { get; set; }
        public string cPsnInPhone { get; set; }
        public string cPsnEmail { get; set; }
        public string cPsnPostAddr { get; set; }
        public string cPsnPostCode { get; set; }
        public string cPsnFAddr { get; set; }
        public string cPsnQQCode { get; set; }
        public string cPsnURL { get; set; }
        public string CpsnOSeat { get; set; }
        public string dEnterUnitDate { get; set; }
        public string cPsnProperty { get; set; }
        public string cPsnBankCode { get; set; }
        public string cPsnAccount { get; set; }
        public System.Guid pk_hr_hi_person { get; set; }
        public Nullable<bool> bProbation { get; set; }
        public string cDutyclass { get; set; }
        public Nullable<bool> bTakeTM { get; set; }
        public string MPictureqpb { get; set; }
        public string rIDType { get; set; }
        public string rCountry { get; set; }
        public string dLeaveDate { get; set; }
        public string rFigure { get; set; }
        public string rWorkStatus { get; set; }
        public string EmploymentForm { get; set; }
        public string rPersonParameters { get; set; }
        public Nullable<bool> bDutyLock { get; set; }
        public Nullable<bool> bpsnshop { get; set; }
        public string CardState { get; set; }
        public string FirstHTBeginDate { get; set; }
        public string LastHTEndDate { get; set; }
        public string cPsn_NameEN { get; set; }
        public Nullable<decimal> sysAge { get; set; }
        public Nullable<decimal> SysCompage { get; set; }
        public Nullable<decimal> SysWorkAge { get; set; }
        public string CRegion { get; set; }
        public string NatrueType { get; set; }
        public string cShiftType { get; set; }
        public string cDefaultBC { get; set; }
        public Nullable<System.DateTime> dEnterDutyClassDate { get; set; }
        public string cRestType { get; set; }
        public string JobNumber { get; set; }
        public string PersonDepart { get; set; }
        public string CardEffectiveBeginTime { get; set; }
        public string CardEffectiveEndTime { get; set; }
        public Nullable<bool> KeyPerson { get; set; }
        public string cLeaveReson { get; set; }
        public string rEmployState { get; set; }
        public string cDutyLocker { get; set; }
        public string cDutyLockerNum { get; set; }
        public string cJobCode { get; set; }
        public string cJobRankCode { get; set; }
        public string cJobGradeCode { get; set; }
        public string cPsnNowAddress { get; set; }
        public string cUrgentPsnName { get; set; }
        public string cUrgentPsnPhone { get; set; }
        public Nullable<bool> bLongIDCard { get; set; }
        public string cLeaveType { get; set; }
        public string cDutyCode { get; set; }
        public string cFax { get; set; }
        public string cTitle { get; set; }
        public string cReportTo { get; set; }
        public string cStartWorkTime { get; set; }
        public string cEndWorkTime { get; set; }
        public string cLoginSubIDs { get; set; }
        public string cpersonbarcode { get; set; }
        public Nullable<bool> bMobileCard { get; set; }
        public string cMobileSites { get; set; }
        public string vOldCard { get; set; }
        public Nullable<int> MaxLeadNum { get; set; }
        public Nullable<int> MaxPAccountNum { get; set; }
        public Nullable<int> MaxAccountNum { get; set; }
        public Nullable<int> MaxOpportunityNum { get; set; }
        public string LeadRcyReg { get; set; }
        public string PAccountRcyReg { get; set; }
        public string OpportunityRcyReg { get; set; }
        public string cESpaceUserID { get; set; }
        public string cWeixinid { get; set; }
        public string chdefine16 { get; set; }
        public string dPayEndDate { get; set; }
    }
}
