//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QMSCRAPDISPOSE
    {
        public QMSCRAPDISPOSE()
        {
            this.QMREJECTVOUCHERS = new HashSet<QMREJECTVOUCHERS>();
        }
    
        public System.Guid SCRAPDISGUID { get; set; }
        public string CSCRAPDISCODE { get; set; }
        public string CSCRAPDISNAME { get; set; }
        public Nullable<int> IDISPOSEFLOW { get; set; }
        public string CMEMO { get; set; }
        public byte[] UFTS { get; set; }
    
        public virtual ICollection<QMREJECTVOUCHERS> QMREJECTVOUCHERS { get; set; }
    }
}
