//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdrecord10_extradefine
    {
        public long ID { get; set; }
        public string chdefine37 { get; set; }
        public string chdefine43 { get; set; }
        public Nullable<double> cHDefine39 { get; set; }
        public Nullable<double> cHDefine40 { get; set; }
    }
}
