//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class U8CUSTDEF_0046_E001
    {
        public string cNo { get; set; }
        public string cDepCode { get; set; }
        public string cCusCode { get; set; }
        public string cPersonCode { get; set; }
        public string cMaker { get; set; }
        public Nullable<System.DateTime> dMakeDateEx { get; set; }
        public Nullable<System.DateTime> dMakeDate { get; set; }
        public string cMender { get; set; }
        public Nullable<System.DateTime> dModifyDateEx { get; set; }
        public Nullable<System.DateTime> dModifyDate { get; set; }
        public string cAuditor { get; set; }
        public Nullable<System.DateTime> dAuditDateEx { get; set; }
        public Nullable<System.DateTime> dAuditDate { get; set; }
        public string cMemo { get; set; }
        public string cReason { get; set; }
        public int U8CUSTDEF_0046_E001_PK { get; set; }
        public Nullable<int> iswfcontrolled { get; set; }
        public Nullable<int> iverifystate { get; set; }
        public Nullable<int> ireturncount { get; set; }
        public Nullable<int> UAPRuntime_RowNO { get; set; }
        public string UAP_VoucherTransform_Rowkey { get; set; }
        public string cReasonU8 { get; set; }
    }
}
