//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherHistory
    {
        public int AutoId { get; set; }
        public string CardNumber { get; set; }
        public Nullable<byte> iRdFlagSeed { get; set; }
        public string cContent { get; set; }
        public string cContentRule { get; set; }
        public string cSeed { get; set; }
        public string cNumber { get; set; }
        public bool bEmpty { get; set; }
    }
}
